---
- hosts: all
  become: yes
  tasks:
    - name: Actualizar cache de apt
      apt:
        update_cache: yes
        
    - name: Instalar Python 3
      apt:
        name: python3
        state: present
        
    - name: Instalar pip para Python 3
      apt:
        name: python3-pip
        state: present
