---
- name: Instalar Docker en objetivo2
  hosts: objetivo2
  become: true
  
  tasks:

    - name: Actualizar cache de apt
      apt:
        update_cache: yes

    - name: Instalar paquetes necesarios para Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Agregar clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Iniciar servicio de Docker
      service:
        name: docker
        state: started
        enabled: yes
